name: Build And Test

on:
  push:
  release:
    types: [published]

jobs:
  build-and-test:
    timeout-minutes: 20
    name: Build
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-22.04] # windows-2022, macos-12,
        include:
          # - os: windows-2022
          #   cmake_command: cmake -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/artifacts ..
          #   build_command: cmake --build build-dir --parallel --target install
          - os: ubuntu-22.04
            cmake_command: cmake -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/artifacts ..
            build_command: cmake --build build-dir --parallel --target install
          # - os: macos-12
          #   cmake_command: cmake -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/artifacts -Dsctp_werror=OFF ..
          #   # 2024-01-05: Sometimes mac fails on github actions when doing builds so we use make without parallellism directly, since we hope that fixes the unknown problem.
          #   build_command: cd build-dir && make -j 1 install

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: install dependencies
        run: sudo apt-get install -y libcurl4-openssl-dev

      - name: Configure cmake
        run: mkdir build-dir && cd build-dir && ${{matrix.cmake_command}}

      - name: Build
        run: ${{matrix.build_command}}

      - name: Test run
        run: ${{ github.workspace }}/artifacts/bin/edge_device_webrtc --help

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts_${{matrix.os}}
          path: ${{ github.workspace }}/artifacts
          if-no-files-found: warn
